name: panda70m_splitting
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.8.16
  - pip
  - pytorch==1.12.1
  - torchvision==0.13.1
  - torchaudio==0.12.1
  - cudatoolkit=11.3
  - pip:
    - -r requirements.txt